export const doctors = [
  {
    id_doctor: 1,
    name: "Dr. Armando Matheus",
    specialty: "Ginecologia e obstetrícia",
    icon: "M",
  },
  {
    id_doctor: 2,
    name: "Dra. Ana Beatriz Rutini",
    specialty: "Cardiologia",
    icon: "F",
  },
  {
    id_doctor: 3,
    name: "Dr. Antônio Almeida Souza",
    specialty: "Pediatria",
    icon: "M",
  },
  {
    id_doctor: 4,
    name: "Dra. Carla Menezes",
    specialty: "Dermatologia",
    icon: "F",
  },
  {
    id_doctor: 5,
    name: "Dr. Henrique Tavares",
    specialty: "Ortopedia",
    icon: "M",
  },
  {
    id_doctor: 6,
    name: "Dra. Larissa Alencar",
    specialty: "Neurologia",
    icon: "F",
  },
  {
    id_doctor: 7,
    name: "Dr. Felipe Nogueira",
    specialty: "Oftalmologia",
    icon: "M",
  },
  {
    id_doctor: 8,
    name: "Dra. Priscila Miranda",
    specialty: "Psicologia",
    icon: "F",
  },
  {
    id_doctor: 9,
    name: "Dr. João Paulo Ramos",
    specialty: "Endocrinologia",
    icon: "M",
  },
  {
    id_doctor: 10,
    name: "Dra. Roberta Silva",
    specialty: "Pneumologia",
    icon: "F",
  },
  {
    id_doctor: 11,
    name: "Dr. Ricardo Martins",
    specialty: "Gastroenterologia",
    icon: "M",
  },
  {
    id_doctor: 12,
    name: "Dra. Júlia Freitas",
    specialty: "Reumatologia",
    icon: "F",
  },
  {
    id_doctor: 13,
    name: "Dr. Eduardo Castro",
    specialty: "Urologia",
    icon: "M",
  },
  {
    id_doctor: 14,
    name: "Dra. Mariana Lopes",
    specialty: "Hematologia",
    icon: "F",
  },
  {
    id_doctor: 15,
    name: "Dr. Bruno Cardoso",
    specialty: "Nefrologia",
    icon: "M",
  },
];

export const appointments = [
  {
    id_appointment: 1,
    service: "Consulta",
    doctor: "Dr. Armando Matheus",
    specialty: "Ginecologia e obstetrícia",
    booking_date: "2024-10-15",
    booking_hour: "08:30",
  },
  {
    id_appointment: 2,
    service: "Consulta",
    doctor: "Dra. Ana Beatriz Rutini",
    specialty: "Cardiologia",
    booking_date: "2024-10-15",
    booking_hour: "09:00",
  },
  {
    id_appointment: 3,
    service: "Consulta",
    doctor: "Dr. Antônio Almeida Souza",
    specialty: "Pediatria",
    booking_date: "2024-10-15",
    booking_hour: "09:30",
  },
  {
    id_appointment: 4,
    service: "Consulta",
    doctor: "Dra. Carla Menezes",
    specialty: "Dermatologia",
    booking_date: "2024-10-16",
    booking_hour: "10:00",
  },
  {
    id_appointment: 5,
    service: "Consulta",
    doctor: "Dr. Henrique Tavares",
    specialty: "Ortopedia",
    booking_date: "2024-10-16",
    booking_hour: "10:30",
  },
  {
    id_appointment: 6,
    service: "Consulta",
    doctor: "Dra. Larissa Alencar",
    specialty: "Neurologia",
    booking_date: "2024-10-16",
    booking_hour: "11:00",
  },
  {
    id_appointment: 7,
    service: "Consulta",
    doctor: "Dr. Felipe Nogueira",
    specialty: "Oftalmologia",
    booking_date: "2024-10-16",
    booking_hour: "11:30",
  },
  {
    id_appointment: 8,
    service: "Consulta",
    doctor: "Dra. Priscila Miranda",
    specialty: "Psicologia",
    booking_date: "2024-10-17",
    booking_hour: "08:30",
  },
  {
    id_appointment: 9,
    service: "Consulta",
    doctor: "Dr. João Paulo Ramos",
    specialty: "Endocrinologia",
    booking_date: "2024-10-17",
    booking_hour: "09:00",
  },
  {
    id_appointment: 10,
    service: "Consulta",
    doctor: "Dra. Roberta Silva",
    specialty: "Pneumologia",
    booking_date: "2024-10-17",
    booking_hour: "09:30",
  },
  {
    id_appointment: 11,
    service: "Consulta",
    doctor: "Dr. Ricardo Martins",
    specialty: "Gastroenterologia",
    booking_date: "2024-10-17",
    booking_hour: "10:00",
  },
  {
    id_appointment: 12,
    service: "Consulta",
    doctor: "Dra. Júlia Freitas",
    specialty: "Reumatologia",
    booking_date: "2024-10-18",
    booking_hour: "10:30",
  },
  {
    id_appointment: 13,
    service: "Consulta",
    doctor: "Dr. Eduardo Castro",
    specialty: "Urologia",
    booking_date: "2024-10-18",
    booking_hour: "11:00",
  },
  {
    id_appointment: 14,
    service: "Consulta",
    doctor: "Dra. Mariana Lopes",
    specialty: "Hematologia",
    booking_date: "2024-10-18",
    booking_hour: "11:30",
  },
  {
    id_appointment: 15,
    service: "Consulta",
    doctor: "Dr. Bruno Cardoso",
    specialty: "Nefrologia",
    booking_date: "2024-10-19",
    booking_hour: "08:30",
  },
  {
    id_appointment: 16,
    service: "Consulta",
    doctor: "Dra. Ana Beatriz Rutini",
    specialty: "Cardiologia",
    booking_date: "2024-10-19",
    booking_hour: "09:00",
  },
  {
    id_appointment: 17,
    service: "Consulta",
    doctor: "Dr. Antônio Almeida Souza",
    specialty: "Pediatria",
    booking_date: "2024-10-19",
    booking_hour: "09:30",
  },
  {
    id_appointment: 18,
    service: "Consulta",
    doctor: "Dra. Carla Menezes",
    specialty: "Dermatologia",
    booking_date: "2024-10-20",
    booking_hour: "10:00",
  },
  {
    id_appointment: 19,
    service: "Consulta",
    doctor: "Dr. Henrique Tavares",
    specialty: "Ortopedia",
    booking_date: "2024-10-20",
    booking_hour: "10:30",
  },
  {
    id_appointment: 20,
    service: "Consulta",
    doctor: "Dra. Larissa Alencar",
    specialty: "Neurologia",
    booking_date: "2024-10-20",
    booking_hour: "11:00",
  },
  {
    id_appointment: 21,
    service: "Consulta",
    doctor: "Dr. Felipe Nogueira",
    specialty: "Oftalmologia",
    booking_date: "2024-10-21",
    booking_hour: "11:30",
  },
  {
    id_appointment: 22,
    service: "Consulta",
    doctor: "Dra. Priscila Miranda",
    specialty: "Psicologia",
    booking_date: "2024-10-21",
    booking_hour: "08:30",
  },
  {
    id_appointment: 23,
    service: "Consulta",
    doctor: "Dr. João Paulo Ramos",
    specialty: "Endocrinologia",
    booking_date: "2024-10-21",
    booking_hour: "09:00",
  },
  {
    id_appointment: 24,
    service: "Consulta",
    doctor: "Dra. Roberta Silva",
    specialty: "Pneumologia",
    booking_date: "2024-10-22",
    booking_hour: "09:30",
  },
  {
    id_appointment: 25,
    service: "Consulta",
    doctor: "Dr. Ricardo Martins",
    specialty: "Gastroenterologia",
    booking_date: "2024-10-22",
    booking_hour: "10:00",
  },
];

export const doctors_services = [
  {
    id_service: 1,
    description: "Consulta Médica",
    price: 500,
  },
  {
    id_service: 2,
    description: "Exame de Sangue",
    price: 150,
  },
  {
    id_service: 3,
    description: "Ultrassonografia",
    price: 300,
  },
  {
    id_service: 4,
    description: "Radiografia",
    price: 250,
  },
  {
    id_service: 5,
    description: "Eletrocardiograma",
    price: 200,
  },
  {
    id_service: 6,
    description: "Consulta Psiquiátrica",
    price: 600,
  },
  {
    id_service: 7,
    description: "Fisioterapia",
    price: 100,
  },
  {
    id_service: 8,
    description: "Consulta Dermatológica",
    price: 400,
  },
  {
    id_service: 9,
    description: "Exame de Audiometria",
    price: 180,
  },
  {
    id_service: 10,
    description: "Sessão de Psicoterapia",
    price: 350,
  },
];

export const horarios = [
  { label: "09:00", value: "09:00" },
  { label: "09:30", value: "09:30" },
  { label: "10:00", value: "10:00" },
  { label: "10:30", value: "10:30" },
  { label: "11:00", value: "11:00" },
  { label: "11:30", value: "11:30" },
  { label: "12:00", value: "12:00" },
  { label: "12:30", value: "12:30" },
  { label: "13:00", value: "13:00" },
  { label: "13:30", value: "13:30" },
  { label: "14:00", value: "14:00" },
  { label: "14:30", value: "14:30" },
  { label: "15:00", value: "15:00" },
  { label: "15:30", value: "15:30" },
  { label: "16:00", value: "16:00" },
  { label: "16:30", value: "16:30" },
  { label: "17:00", value: "17:00" },
  { label: "17:30", value: "17:30" },
  { label: "18:00", value: "18:00" },
];